[package]
name = "currspice_mods"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.15", features = ["blocking"]}
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
